/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 02 21:21:53 GMT 2026
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.EmptyStackException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Stack;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Stack_ESTest extends Stack_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Stack<Object> stack0 = new Stack<Object>();
      Stack<String> stack1 = new Stack<String>();
      stack1.push("iA\"$YJ+7|");
      stack1.pop();
      stack0.push("cA0tI");
      assertFalse(stack0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      stack0.push("iA\"$YJ+7|");
      stack0.pop();
      assertTrue(stack0.isEmpty());
      
      Stack<String> stack1 = new Stack<String>();
      assertTrue(stack1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Stack<Integer> stack0 = new Stack<Integer>();
      stack0.isEmpty();
      Stack<Object> stack1 = new Stack<Object>();
      assertTrue(stack1.isEmpty());
      
      Object object0 = new Object();
      stack1.push(object0);
      assertFalse(stack1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Stack<Integer> stack0 = new Stack<Integer>();
      stack0.isEmpty();
      Stack<Object> stack1 = new Stack<Object>();
      // Undeclared exception!
      try { 
        stack1.pop();
        fail("Expecting exception: EmptyStackException");
      
      } catch(EmptyStackException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Stack<Object> stack0 = new Stack<Object>();
      Object object0 = new Object();
      stack0.push(object0);
      assertFalse(stack0.isEmpty());
      
      stack0.pop();
      boolean boolean0 = stack0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Stack<Integer> stack0 = new Stack<Integer>();
      assertTrue(stack0.isEmpty());
      
      Integer integer0 = new Integer((-1));
      stack0.push(integer0);
      boolean boolean0 = stack0.isEmpty();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      stack0.push("");
      stack0.push("Zy*q7+!Y#rX@D\";QRh|");
      stack0.push("");
      stack0.push("E5]uUFVGF?w/GgHu7");
      stack0.push("");
      stack0.push("");
      stack0.push((String) null);
      stack0.push("");
      stack0.push("h_24eb4\"X");
      stack0.push((String) null);
      // Undeclared exception!
      try { 
        stack0.push((String) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Stack exceeded capacity!
         //
         verifyException("tutorial.Stack", e);
      }
  }
}
