/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 02 16:54:19 GMT 2026
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Node;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Node_ESTest extends Node_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Node<Object> node0 = new Node<Object>("m");
      node0.setNext((Node<Object>) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Node<String> node0 = new Node<String>("E:OnWQwHJky[(");
      String string0 = node0.getObject();
      assertEquals("E:OnWQwHJky[(", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Node<Object> node0 = new Node<Object>("m");
      Node<Object> node1 = node0.getNext();
      assertNull(node1);
  }
}
